### ISSUE TITLE
Readme notes regarding existing changes in repo Gitodo is being added to.

### ISSUE THREAD

**Issue by tw2113** [kayladnls/gitodo#2]
May not be a bad idea to make note that any pending changes in someone's repo will be committed when adding Gitodo, so users will probably want to start this with a clean working directory.

**Comment by tw2113** [comment]
As an alternative, somehow highlight more prominently the -h flag that won't commit everything right away

**Comment by greydnls** [comment]
Sure, I can move the -h flag up. 

I could also add a convention to mark these files as being todo files, and only commit those files. Thoughts on that?

Something like this: 

--gitodo--

# File Name

### First Sublist
- todo

**Comment by tw2113** [comment]
I like the only committing the todo files idea, since it sounds like it'd be possible.

**Comment by greydnls** [comment]
I've got this implemented now. Feel free to repoen if you have an issue with it.
